import { Footer } from "@/packages/shared/common";
import Navbar from "@/packages/shared/common/navbar/Navbar";
import {
  madaniThin,
  madaniExtraLight,
  madaniLight,
  madaniRegular,
  madaniMedium,
  madaniSemiBold,
  madaniBold,
  madaniExtraBold,
  madaniBlack,
} from "@/packages/shared/themes/fonts";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const fontVariables = [
    madaniThin.variable,
    madaniExtraLight.variable,
    madaniLight.variable,
    madaniRegular.variable,
    madaniMedium.variable,
    madaniSemiBold.variable,
    madaniBold.variable,
    madaniExtraBold.variable,
    madaniBlack.variable,
  ].join(" ");

  return (
    <html lang="en" className={fontVariables}>
      <body style={{ margin: 0 }}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
